# Generated by Django 4.1 on 2024-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_catalogue_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='prix',
            field=models.FloatField(),
        ),
    ]
