# Generated by Django 4.1 on 2024-08-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cartorderproducts_invoice_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product_status',
        ),
    ]
