# Generated by Django 4.1 on 2024-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_prix_catalogue_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='price',
            new_name='prix',
        ),
    ]
