# Generated by Django 4.1 on 2024-10-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_price_catalogue_prix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
