# Generated by Django 4.1 on 2024-10-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
