# Generated by Django 4.1 on 2024-10-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
        ('core', '0014_alter_address_country'),
    ]

    operations = [
    ]
