# Generated by Django 4.1 on 2024-10-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0002_contact_0014_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ville',
            field=models.CharField(default='ville', max_length=100),
            preserve_default=False,
        ),
    ]
