# Generated by Django 4.1 on 2024-10-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_address_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
