# Generated by Django 4.1 on 2024-10-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_address_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ville',
        ),
    ]
