# Generated by Django 4.1 on 2024-10-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_address_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
