# Generated by Django 4.1 on 2024-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_address_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='whatsapp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
