# Generated by Django 4.1 on 2024-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cartorder_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproducts',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
