# Generated by Django 4.1 on 2024-11-07 09:46

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cartorderproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='whatsapp',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', blank=True, length=5, max_length=20, null=True, prefix='RGM'),
        ),
    ]
